name: first workflow
on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "Hello world"
        
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: print bye
        run: echo "bye world"
        
